config/routes.rb
Rails.application.routes.draw do
  resources :donations
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'donations#index'
  get '/groups', to: 'groups#index'
  get '/schedule', to: 'schedule#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/donation.rb
class Donation < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  before_action :set_donation, only: [:show, :edit, :update, :destroy]

  #USER_ID, PASSWORD = "zara", "pass123"

# ********Require authentication only for edit and delete operation
   #before_filter :authenticate, :only => [ :edit, :delete ]

  # GET /donations
  # GET /donations.json
  def index
    @donations = Donation.all
  end

  # GET /donations/1
  # GET /donations/1.json
  def show
    @donation = Donation.find(params[:id])
  end

  # GET /donations/new
  def new
    @donation = Donation.new
  end

  # GET /donations/1/edit
  def edit
  end

  # POST /donations
  # POST /donations.json
  def create
    @donation = Donation.new(donation_params)

    respond_to do |format|
      if @donation.save
        format.html { redirect_to @donation, notice: 'Donation was successfully created.' }
        format.json { render :show, status: :created, location: @donation }
      else
        format.html { render :new }
        format.json { render json: @donation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /donations/1
  # PATCH/PUT /donations/1.json
  def update
    respond_to do |format|
      if @donation.update(donation_params)
        format.html { redirect_to @donation, notice: 'Donation was successfully updated.' }
        format.json { render :show, status: :ok, location: @donation }
      else
        format.html { render :edit }
        format.json { render json: @donation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /donations/1
  # DELETE /donations/1.json
  def destroy
    @donation.destroy
    respond_to do |format|
      format.html { redirect_to donations_url, notice: 'Donation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_donation
      @donation = Donation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def donation_params
      params.require(:donation).permit!
    end
end

#private  **************
   #def authenticate
      #authenticate_or_request_with_http_basic do |id, password|
         #id == USER_ID && password == PASSWORD
      #end
   #end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def index
  end

end

app/controllers/schedule_controller.rb
class ScheduleController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/donations_helper.rb
module DonationsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/schedule_helper.rb
module ScheduleHelper
end

app/views/donations/_form.html.erb
<%= form_with(model: donation, local: true) do |form| %>
  <% if donation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(donation.errors.count, "error") %> prohibited this donation from being saved:</h2>
      <ul>
        <% donation.error_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.label :first_name %>
  <%= form.text_field :first_name %>

  <%= form.label :last_name %>
  <%= form.text_field :last_name %>

  <%= form.label :zip_code %>
  <%= form.text_field :zip_code %>

  <%= form.label :phone_number %>
  <%= form.text_field :phone_number %>

  <%= form.label :email %>
  <%= form.text_field :email %>

  <%= form.label :donation_category %>
  <%= form.text_field :donation_category %>

  <%= form.label :item %>
  <%= form.text_field :item %>

  <%= form.label :quantity %>
  <%= form.number_field :quantity %>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/donations/edit.html.erb
<h1>Editing Donation</h1>

<%= render 'form', donation: @donation %>

<%= link_to 'Show', @donation %> |
<%= link_to 'Back', donations_path %>

app/views/donations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Donations</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @donations.each do |donation| %>
      <tr>
        <td><%=donation.first_name %></td>
        <td><%=donation.last_name %></td>
        <td><%=donation.zip_code %></td>
        <td><%=donation.phone_number %> &nbsp; &nbsp; </td>
        <td><%=donation.email %></td>
      </tr>
      <tr>
        <td><%=donation.donation_category %> &nbsp; &nbsp; </td> 
        <td><%=donation.item %> &nbsp; &nbsp; </td>
        <td><%=donation.quantity %> &nbsp; &nbsp; </td>
        <td><%=donation.notes %></td>
      </tr>
      <tr>
        <td><%= link_to 'Show', donation %></td>
        <td><%= link_to 'Edit', edit_donation_path(donation) %></td>
        <td><%= link_to 'Destroy', donation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Donation', new_donation_path %>

app/views/donations/new.html.erb
<h1>New Donation</h1>

<%= render 'form', donation: @donation %>

<%= link_to 'Back', donations_path %>

app/views/donations/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_donation_path(@donation) %> |
<%= link_to 'Back', donations_path %>

<h1><%= @donation.first_name                                                                                                                           %></h1>
Info:
<ul>
  <li>Location: <%= @donation.zip_code %></li>
  <li>Donation category: <%= @donation.donation_category %></li>
  <li>Item: <%= @donation.item %></li>
  <li>Quantity: <%= @donation.donation_category %></li>
</ul>

app/views/groups/index.html.erb
<h1> Groups </h1>
<li> The Forgotten Louisville </li>
<li> Hip Hop Cares </li>
<li> Share the Love Outreach </li>
<li> Southend Street Angels </li>
<li> Fern Creek United Methodist </li>
<li> Keep Louisville Warm </li>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <% link_to 'outreach', root_path %>
  <div class="container" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link active" href="/">Home <span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link" href="/groups">Groups</a>
      <a class="nav-item nav-link" href="/donations">Donate Supplies</a>
      <a class="nav-item nav-link" href="/schedule">Serve Schedule</a>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Outreach</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<h1>LouisvilleOutreach.org</h1>

app/views/schedule/index.html.erb
<h1> Schedule </h1>
<ul> Monday </ul>
<ul> Tuesday </ul>
<ul> Wednesday </ul>
<ul> Thursday </ul>
<ul> Friday </ul>
<ul> Saturday </ul>
<ul> Sunday </ul>